### ISSUE TITLE
terminal getting swallowed using dmenu

### ISSUE THREAD

**Issue by ehula** [Liupold/pidswallow#1]
If my terminal is focused and I launch a program using dmenu, the terminal is being swallowed. That shouldn't be happening. The terminal should only be swallowed if I launch a program using the terminal.

**Comment by Liupold** [comment]
What are you launching from `dmenu` ? is it something opening in terminal (terminal program)?

**Comment by ehula** [comment]
Oops. My bad. I was trying another developer's version of this script, and apparently it was still running when trying yours. Now that I have disabled that other one, I find yours is working just fine. And fast! The other one has the problem I described. Thanks for a great script!

**Comment by Liupold** [comment]
Thanks. (I had the exact same problem hence i made this).
