### ISSUE TITLE
Unable to swallow Konsole on Plasma

### ISSUE THREAD

**Issue by SeerLite** [Liupold/pidswallow#20]
```
$ pstree -ATlsp $$
systemd(1)---plasmashell(4588)---konsole(39639)---zsh(39645)---pstree(39710)
$ xdotool search --pid 39639                                    
73400321
73400323
73400362
73400382
71303175
```
For some reason, even though there's only 1 konsole instance with 1 konsole window, multiple WIDs are output (from the same PID!)
This is really confusing me. I'll check it out later.

Testing plasma also led me to find out about another issue ~~that seems to happen even on the master branch~~ _nope, only DEs_, so I'll check that first. Edit: Fixed that one

**Comment by SeerLite** [comment]
Same issue with `xfce4-terminal` on XFCE. Not sure how to deal with this.

**Comment by Liupold** [comment]
I'm not 100% on this but I think we can short , (window ID will increase) from parent to child. I am going to try that today and have a look. Sorry my time zone is different.

**Comment by Liupold** [comment]
fixed on: https://github.com/Liupold/pidswallow/commit/a50ec465ed3e1f4ee12993461ee440e9183bb9cc

**Comment by SeerLite** [comment]
Looks like I didn't test well enough yesterday...

**Comment by SeerLite** [comment]
[Here's a video of some quick tests I did](https://0x0.st/ixva.mp4)

Edit: Running latest (b931a771dfc8b6279eefc98d46c7986ae188d110) with $TERMINAL as alacritty (that's why alacritty works)
Edit: XFCE produces the same weird window for xfce4-terminal:
![image](https://user-images.githubusercontent.com/21978144/89069588-6e97d280-d341-11ea-848e-4f784c369a93.png)

**Comment by SeerLite** [comment]
Okay I figured something out. Everytime I tested, the "real" konsole window was the lowest number WID from `xdotool search`. In bspwm, this one is always the first, but in Plasma, it's usually the last one instead (no clue why!)
I think we're either gonna have to sort the WIDS by value and use the lowest one or check every WID for a real mapped window and use the one that is.

**Comment by SeerLite** [comment]
https://0x0.st/ixvY.patch worked for Konsole/Plasma but not for XFCE. I think we're gonna have to check each individually. I wonder if there's any `xdotool` command for that.

**Comment by SeerLite** [comment]
I feel so stupid now...
>            --onlyvisible
>               Show only visible windows in the results. This means ones with
>               map state IsViewable.


---
Btw: Sorry for the possible spam. I just realized I've been replying to myself a lot and I could have done all these tests in one go and put the results later.

**Comment by Liupold** [comment]
> [Here's a video of some quick tests I did](https://0x0.st/ixva.mp4)
> 
> Edit: Running latest ([b931a77](https://github.com/Liupold/pidswallow/commit/b931a771dfc8b6279eefc98d46c7986ae188d110)) with $TERMINAL as alacritty (that's why alacritty works)
> Edit: XFCE produces the same weird window for xfce4-terminal:
> ![image](https://user-images.githubusercontent.com/21978144/89069588-6e97d280-d341-11ea-848e-4f784c369a93.png)

Damn I got Rick rolled!

**Comment by SeerLite** [comment]
Sorry about that ;)
