### ISSUE TITLE
XFCE terminal won't work because every instance shares the same PID

### ISSUE THREAD

**Issue by SeerLite** [Liupold/pidswallow#22]
It's a bummer but I think we just can't support that one.

**Comment by Liupold** [comment]
It's like `urxvtd`. Is there any way to fork it ? (If not we will be adding that to not supported list).

**Comment by SeerLite** [comment]
What do you mean with "fork it"?

**Comment by Liupold** [comment]
```
xfce4-terminal --disable-server
```
https://forum.xfce.org/viewtopic.php?id=12691

**Comment by SeerLite** [comment]
That works! Do you think it should be noted as a necessary workaround in the README? Still sad we can't make it work out of the box :/

**Comment by Liupold** [comment]
Yes, it's works on a client server model by default. We can guide them to make a desktop shortcut. (As most of xfce4-terminal user will not use some kind of keyboard daemon).

**Comment by SeerLite** [comment]
Makes sense! My only concern is if there's any side effects to doing this (e.g. missing XFCE terminal functions)

**Comment by SeerLite** [comment]
What do you think of 63460ab6a15a3fc4dbf3d365b71b55525bcffaed (xfce-instructions branch)?

**Comment by Liupold** [comment]
Couldn't do better. Awesome.

> What do you think of [63460ab](https://github.com/Liupold/pidswallow/commit/63460ab6a15a3fc4dbf3d365b71b55525bcffaed) (xfce-instructions branch)?

**Comment by Liupold** [comment]
After merging remove the 'experimental' warning.
