### ISSUE TITLE
Sub-windows re-swallowing an alraedy swallowed parent

### ISSUE THREAD

**Issue by SeerLite** [Liupold/pidswallow#23]
It happens because our only check for a window already being swallowed is [this line](https://github.com/Liupold/pidswallow/blob/7d69a05098191dd456208e7dd419d1de137f0933/pidswallow#L31), which only checks if the current child window (`cwid`) has any window swallowed.

In the case of sub-windows (e.g. when a program creates a pop-up window), the child window will be different to the one that originally swallowed. This causes pidswallow to think it's our first time swallowing it and proceeds to do it again.

This isn't noticeable with default configuration because `xdotool unmapwindow` will just fail and not do anything. However, when using the [recommended bspwm-specific configuration](https://github.com/Liupold/pidswallow/tree/dev#bspwm), `bspc node {%pwid} --flag hidden=on` has a very different result when `{%pwid}` is left as blank.

Right now it's late for me so this looks like a hard thing to solve, maybe even requiring some changes to how the `/tmp` files are handled. But I might wake up tomorrow and realize it's some easy check.

**Comment by SeerLite** [comment]
Ok I fixed it, technically. Some other issues might come up related to this later though. For example, when the sub-window becomes the main window and the first window is closed: the terminal would get vomited even though there's still windows.

**Comment by Liupold** [comment]
We can check if parent is visible.

**Comment by SeerLite** [comment]
What do you mean?

**Comment by Liupold** [comment]
> What do you mean?

if the sub window become the main window the window id will be different.
(and it will vomit, seems like correct behavior)

we are checking (i forgot) if the parent is visible during swallowing. `--only-visible` .
`[ -z "$pwid" ] && return 4` is the best we can do.

**Comment by SeerLite** [comment]
> if the sub window become the main window the window id will be different.
> (and it will vomit, seems like correct behavior)

IMO terminal should only be vomited when there's no windows left. But yeah, there's all kinds of crazy GUI out there that handle their windows in weirdest way. I wouldn't worry too much about it for now unless someone complains.
