### ISSUE TITLE
Issue with dmenu

### ISSUE THREAD

**Issue by Monklite** [Liupold/pidswallow#3]
There is probably some sort of work-around for this, but I think it's worth bringing up.

If I open dmenu to open something like firefox while the current focused window is a terminal that is whitelisted (in my case, st), the terminal swallows the program despite being launched from dmenu instead of from the terminal.

Is there a workaround for this? Thanks

EDIT: Oops, I'm commenting on the wrong project but since I'm here, I'll try this out too :)

**Comment by Liupold** [comment]
This project prevents that.  Hope you like it. Similar issue : #1. Feel free to close the issue after your tried it.

**Comment by Liupold** [comment]
closing.
