### ISSUE TITLE
Configuration for re-focusing parent window when vomiting child

### ISSUE THREAD

**Issue by SeerLite** [Liupold/pidswallow#32]
What do you think of adding a configuration option for this? I personally like the parent to always regain focus.
Another idea I have is to monitor the child window focus. And only if it was focused when it closed, re-focus the parent. This feels like overkill though.

**Comment by Liupold** [comment]
This is overkill, This is how focus is actually working , (except for bspwm).

**Comment by Liupold** [comment]
I like the way it is working now no complains. 🎊

**Comment by SeerLite** [comment]
> This is overkill, This is how focus is actually working , (except for bspwm).

But that's a side effect of `windowmap`, isn't it? Doesn't it ask for focus everytime (same as if using `bspc node -f`)?

**Comment by Liupold** [comment]
Ya, how can it be better? BTW do you have a public email or should I link your github profile in man?

**Comment by SeerLite** [comment]
> Ya, how can it be better?

Still looking into it :P

> BTW do you have a public email or should I link your github profile in man?

Oh o.o I didn't of that. You can use the one I use for github: seerlite@tuta.io

**Comment by Liupold** [comment]
Checkout the man page.
[pidswallow.man1.pdf](https://github.com/Liupold/pidswallow/files/5013625/pidswallow.man1.pdf)

**Comment by SeerLite** [comment]
Oh, that's looking real nice!

**Comment by Liupold** [comment]
It might not be  a overkill. We  could have a loop which just save last two focus to some file in tmp and then checks during vomit.

**Comment by Liupold** [comment]
It is not possible, (In my opinion). As the child focus will change when the window is closed. And if we check the second last window id in list it will still be not possible as the focus move might be intentional by the user. I am out of ideas ( for now ). If you have something pls let me know, else close this issue... (I think what you wanted is already added on 4669203b264d17d227873ddeedcf1d89a9d5ba26. ).

**Comment by Liupold** [comment]
@SeerLite if this is resolve you might wan't to close this. fixed on: 4669203b264d17d227873ddeedcf1d89a9d5ba26 (hopefully).

**Comment by SeerLite** [comment]
Yeah, you're right, that works for me! Sorry for the inactivity lately :
