### ISSUE TITLE
xprop -spy doesn't detect window changes

### ISSUE THREAD

**Issue by SeerLite** [Liupold/pidswallow#34]
`xprop -spy` only outputs lines when windows are focused. I'm not sure if this is intended.
I hadn't noticed this before because I have a special keybind that does something every once in a while that also triggers `xprop -spy`.

This is a problem in bspwm, for example, where moving the window around won't update the position and resizing won't update the size.

Edit: to reproduce, have a floating terminal and move it around with super + mouse (assuming that config hasn't been changed). Launching anything from that terminal will use the old position and not the new one.

Edit: I just realized it's kind of program-dependant. For instance, I'm testing Alacritty.

**Comment by Liupold** [comment]
No this is not intended and i know about this. I am not aware of any solution, Feel free to fix / change `xprop -spy`

**Comment by SeerLite** [comment]
Yup that's the problem right now. I don't know any tool that can "subscribe" to window events independently of the WM in use. Maybe adding a new WM-specific variable (this is getting ridiculous though) for subscribing to window events (`bspc subscribe`/`i3-msg -t subscribe`)?

**Comment by Liupold** [comment]
> Yup that's the problem right now. I don't know any tool that can "subscribe" to window events independently of the WM in use. Maybe adding a new WM-specific variable (this is getting ridiculous though) for subscribing to window events (`bspc subscribe`/`i3-msg -t subscribe`)?

Nope! no more wm specific variable. (I will have nightmares).

**Comment by SeerLite** [comment]
Alright :S but something has to be done though. I'll test `xprop -spy` a bit more before looking for something new

**Comment by Liupold** [comment]
`xev -1 -root -geometry 0x0` maybe ? 0_O (but it is stupid)

**Comment by Liupold** [comment]
Here you go:
`xev -id <WID>  -1 -geometry 0x0 -event structure`

**Comment by Liupold** [comment]
> Here you go:
> `xev -id <WID> -1 -geometry 0x0 -event structure`

We can extract the size and pos from this.

**Comment by SeerLite** [comment]
Wow you are really fast!
How did you even discover this?

**Comment by Liupold** [comment]
by playing around with xorg. (I like to play around with stuff)

**Comment by SeerLite** [comment]
Check out this nasty sed regex I came up with:

    xev -id "$(bspc query -N -n)" -1 -geometry 0x0 -event structure | sed -e 's/.*(\(-\?[0-9]\+\),\(-\?[0-9]\+\)),/\1 \2/' -e 's/width \([0-9]\+\), height \([0-9]\+\).*/\1 \2/'

**Comment by SeerLite** [comment]
I can't believe I did all that thinking only BRE was POSIX and now reading [this](https://www.gnu.org/software/sed/manual/html_node/BRE-vs-ERE.html#BRE-vs-ERE) I realize ERE is also POSIX.

Yeah.. I'm making that more readable

Edit: ERE variant:

    xev -id "$(bspc query -N -n)" -1 -geometry 0x0 -event structure | sed -E -e 's/.*\((-?[0-9]+),(-?[0-9]+)\),/\1 \2/' -e 's/width ([0-9]+), height ([0-9]+).*/\1 \2/'

**Comment by Liupold** [comment]
> ```
> xev -id "$(bspc query -N -n)" -1 -geometry 0x0 -event structure | sed -E -e 's/.*\((-?[0-9]+),(-?[0-9]+)\),/\1 \2/' -e 's/width ([0-9]+), height ([0-9]+).*/\1 \2/'
> ```

we don't need `-geometry 0x0`,


It's great now we can put everything in one file.

**Comment by SeerLite** [comment]
Ok, this is gonna sound really dumb now, but I've been fighting with `read` for the last minutes (trying to do `read -r x y width height`) but the thing just won't work. I'm losing my mind rn

I'm using `mrsh` and `dash` (both POSIX) to test, and none of them give any output with

    xev -id "$(bspc query -N -n)" -1 -event structure | sed -E -e 's/.*\((-?[0-9]+),(-?[0-9]+)\),/\1 \2/' -e 's/width ([0-9]+), height ([0-9]+).*/\1 \2/' | while read -r x y width height; do echo $x $y $width $height; done

**Comment by Liupold** [comment]
read the event and then use sed.

**Comment by Liupold** [comment]
`<xev....> | while read -r event `

**Comment by SeerLite** [comment]
Yeah that sounds like a solution. _Feels_ a bit slower though, doesn't it? The whole point of `read` is to "split" the input into the variables.

**Comment by Liupold** [comment]
you might want to push that branch to github. so i can look into it

**Comment by SeerLite** [comment]
> read the event and then use sed.

Wait but how do I set them up for each variable after that

**Comment by Liupold** [comment]
> > read the event and then use sed.
> 
> Wait but how do I set them up for each variable after that

well it's a bit confusing, let me know after you push,

**Comment by SeerLite** [comment]
[xev-subscribe branch](https://github.com/Liupold/pidswallow/tree/xev-subscribe) is what I got going on so far

**Comment by Liupold** [comment]
65cfa81 fixed it., you need some sleep i guess.

**Comment by SeerLite** [comment]
I had no idea about `-u`. You're amazing

**Comment by Liupold** [comment]
fixed on #35
