### ISSUE TITLE
Daemon Based Terminal Will not work

### ISSUE THREAD

**Issue by Liupold** [Liupold/pidswallow#36]
A lot of the terms are dbus based, (This will not work correctly)

* urxvtd (daemon #17)
* xfce-terminal
* gnome-termiinal

We probably need to maintain a list of this,

**Comment by SeerLite** [comment]
AFAIK urxvtd isn't really "dbus", just "daemon mode".
The issue is more about "daemon managed" terminals than dbus.

**Comment by Liupold** [comment]
Ya they just use Dbus for communication.

**Comment by Liupold** [comment]
A fix is on the way.

**Comment by Liupold** [comment]
Fixed 40104a9c3663946f32af40afa3d9878cd5239976
