### ISSUE TITLE
Instructions for Xfce Terminal don't work globally.

### ISSUE THREAD

**Issue by SeerLite** [Liupold/pidswallow#38]
Opening the terminal from somewhere other than the application finder (e.g. through `exo-open`, by defining the Xfce Terminal as a "default application") won't use the `--disable-server` flag. I'm not sure how to set it up.

**Comment by Liupold** [comment]
Its best we can do, I don't think there is way for that other that making a custom `xfce4-terminal` script in path bad idea. , IMO

**Comment by Liupold** [comment]
I think we should pin the daemon terminal not working issue.

**Comment by Liupold** [comment]
check this out https://github.com/Liupold/pidswallow/tree/daemon-fix

**Comment by Liupold** [comment]
closing...
