### ISSUE TITLE
Doesn't work if sxhkd is run as a systemd service.

### ISSUE THREAD

**Issue by SeerLite** [Liupold/pidswallow#5]
Hi!
I'm using sxhkd as a [systemd user service](https://github.com/baskerville/sxhkd/blob/master/contrib/systemd/sxhkd.service). I've made a small modification to the unit too (`KillMode=process`).

The thing is, this makes systemd the "parent" process. Running `pidswallow` with `verbose=1` on an Alacritty window gives this output:
```
systemd(724)---alacritty(25793)---zsh(25799)
```
Thus, the script doesn't work.
I tried messing around with the script for a bit, but I don't know much about process handling and the variable names just confused me more. So I gave up and made an issue.

Is there a way to work around this?

**Edit:** I'm honestly not sure if systemd has anything to do with it. I'm just assuming here (sorry if I'm wrong), since using a simpler `sxhkd &` inside bspwmrc doesn't cause any problems.

**Comment by Liupold** [comment]
I don't think its a problem with sxhkd. your pstree output looks what it should be. Launch a gui app from terminal (Eg: `mpv`). And then  provide the verbose output. If it works perfectly launching from term let me know. (As i intend to make the installation more simple).

**Comment by SeerLite** [comment]
Alright here's me starting Alacritty from a sxhkd shortcut, and running mpv.

systemd (`sxhkd.service`):
```sh
$ bspc subscribe node_add node_remove | grep -o --line-buffered '0x[0-9A-F]\+$' | xargs -n1 ./pidswallow
systemd(727)---alacritty(3425)---zsh(3430)
systemd(727)---alacritty(3425)---zsh(3430)---mpv(3535)
```

bspwmrc autostart (`sxhkd &`):
```sh
$ bspc subscribe node_add node_remove | grep -o --line-buffered '0x[0-9A-F]\+$' | xargs -n1 ./pidswallow
alacritty(6485)---zsh(6493)
alacritty(6485)---zsh(6493)---mpv(6570)
mpv(0x06A00002) swallowed alacritty(100663300)
0x06A00002 vomited 100663300
```

As you can see, it works if sxhkd is not a systemd service.

**Comment by SeerLite** [comment]
Ok, I finally understand the script completely haha. So yeah, the problem here is indeed systemd is in the way. But more importantly, the problem is we're not swallowing the immediate parents.

This problem can also be reproduced by running a terminal process inside another terminal process. The first terminal is gonna get swallowed, while it should be the second one.

I found [this](https://superuser.com/questions/150117/how-to-get-parent-pid-of-a-given-process-in-gnu-linux-from-command-line). I think this is a great way to implement it, since it doesn't rely on `pstree` output. I'll play around with it and if it works I'll create a pull request.
